name: Deploy documentation site

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    uses: UrbanCode/reusable-workflows/.github/workflows/mkdocs-deploy.yml@main